services:
  - type: web
    name: cms-backend
    env: java
    plan: free
    rootDir: .
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/cmsproject-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_ADMIN_SECRET
        sync: false
